Removed all mentions of "please" from docs and messages #770
Signed-off-by: Grace Choi <gracechoi@utexas.edu>
Signed-off-by: Pranjal Rai <pranjalrai@utexas.edu>

diff --git a/dockerfiles/Dockerfile.authors b/dockerfiles/Dockerfile.authors
--- a/dockerfiles/Dockerfile.authors
+++ b/dockerfiles/Dockerfile.authors
@@ -18,7 +18,7 @@ git add -A
 cp -rf /out/* .
 diff=$(git status --porcelain -- AUTHORS)
 if [ -n "$diff" ]; then
-  echo >&2 'ERROR: Authors result differs. Please update with "make -f docker.Makefile authors"'
+  echo >&2 'ERROR: Authors result differs. Update with "make -f docker.Makefile authors"'
   echo "$diff"
   exit 1
 fi
diff --git a/scripts/vendor b/scripts/vendor
--- a/scripts/vendor
+++ b/scripts/vendor
@@ -29,7 +29,7 @@ update() {
 validate() {
   diff=$(git status --porcelain -- vendor.mod vendor.sum vendor)
   if [ -n "$diff" ]; then
-    echo >&2 'ERROR: Vendor result differs. Please vendor your package with "make -f docker.Makefile vendor"'
+    echo >&2 'ERROR: Vendor result differs. Vendor your package with "make -f docker.Makefile vendor"'
     echo "$diff"
     exit 1
   fi
